if (NOT INPUT_FILE OR NOT OUTPUT_FILE OR NOT VARIABLE_NAME)
    message(FATAL_ERROR "INPUT_FILE, OUTPUT_FILE and VARIABLE_NAME must be defined")
endif()

file(READ ${INPUT_FILE} SHADER_CONTENT)
file(WRITE ${OUTPUT_FILE} "const char ${VARIABLE_NAME}[] = R\"(${SHADER_CONTENT})\";")